name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: init project
      run: sudo apt-get install -y make
    - run: make init
    - name: Docker compose up
      run: docker-compose up -d
